import type { EnvVarSchema, InferredType } from "./types.js";

function tsType(schema: EnvVarSchema): string {
  switch (schema.type) {
    case "string":
    case "email":
      return "string";
    case "number":
    case "integer":
    case "port":
      return "number";
    case "boolean":
      return "boolean";
    case "url":
      return "string";
    case "enum":
      if (schema.enumValues) {
        return schema.enumValues.map((v) => `"${v}"`).join(" | ");
      }
      return "string";
  }
}

function parseExpression(schema: EnvVarSchema): string {
  const raw = `process.env.${schema.name}`;

  switch (schema.type) {
    case "number":
    case "integer":
    case "port":
      if (schema.defaultValue !== undefined) {
        return `Number(${raw} ?? ${JSON.stringify(schema.defaultValue)})`;
      }
      return schema.required ? `Number(${raw}!)` : `${raw} ? Number(${raw}) : undefined`;

    case "boolean":
      if (schema.defaultValue !== undefined) {
        return `["true", "1", "yes"].includes((${raw} ?? ${JSON.stringify(schema.defaultValue)}).toLowerCase())`;
      }
      return schema.required
        ? `["true", "1", "yes"].includes(${raw}!.toLowerCase())`
        : `${raw} ? ["true", "1", "yes"].includes(${raw}.toLowerCase()) : undefined`;

    case "url":
    case "email":
    case "string":
      if (schema.defaultValue !== undefined) {
        return `${raw} ?? ${JSON.stringify(schema.defaultValue)}`;
      }
      return schema.required ? `${raw}!` : raw;

    case "enum": {
      const value = schema.defaultValue !== undefined
        ? `${raw} ?? ${JSON.stringify(schema.defaultValue)}`
        : schema.required ? `${raw}!` : raw;
      if (schema.enumValues) {
        const allowed = schema.enumValues.map((v) => `"${v}"`).join(", ");
        return `(([${allowed}] as const).includes(${value} as any) ? ${value} : (() => { throw new Error(\`Invalid ${schema.name}: \${${value}}\`); })()) as ${tsType(schema)}`;
      }
      return value;
    }
  }
}

export function generateEnvModule(schemas: EnvVarSchema[]): string {
  const lines: string[] = [
    "// Auto-generated by envtypes. Do not edit manually.",
    "// Regenerate with: npx envtypes generate",
    "",
  ];

  // Interface
  lines.push("export interface Env {");
  for (const schema of schemas) {
    const type = tsType(schema);
    const optional = schema.required ? "" : "?";
    if (schema.description) {
      lines.push(`  /** ${schema.description} */`);
    }
    lines.push(`  ${schema.name}${optional}: ${type};`);
  }
  lines.push("}", "");

  // Validated env object
  lines.push("function loadEnv(): Env {");
  lines.push("  const missing: string[] = [];");
  lines.push("");

  const required = schemas.filter((s) => s.required && s.defaultValue === undefined);
  if (required.length > 0) {
    for (const schema of required) {
      lines.push(
        `  if (!process.env.${schema.name}) missing.push("${schema.name}");`
      );
    }
    lines.push("");
    lines.push("  if (missing.length > 0) {");
    lines.push(
      '    throw new Error(`Missing required environment variables: ${missing.join(", ")}`);'
    );
    lines.push("  }");
    lines.push("");
  }

  lines.push("  return {");
  for (const schema of schemas) {
    lines.push(`    ${schema.name}: ${parseExpression(schema)},`);
  }
  lines.push("  };");
  lines.push("}", "");

  lines.push("export const env = loadEnv();", "");

  return lines.join("\n");
}

export function generateEnvExample(schemas: EnvVarSchema[]): string {
  const lines: string[] = [
    "# Auto-generated by envtypes. Do not edit manually.",
    "# Regenerate with: npx envtypes generate",
    "",
  ];

  const required = schemas.filter((s) => s.required);
  const optional = schemas.filter((s) => !s.required);

  if (required.length > 0) {
    lines.push("# Required");
    for (const schema of required) {
      const example = exampleValue(schema);
      lines.push(`${schema.name}=${example}`);
    }
  }

  if (optional.length > 0) {
    lines.push("", "# Optional");
    for (const schema of optional) {
      const example = exampleValue(schema);
      const defaultNote =
        schema.defaultValue !== undefined
          ? ` (default: ${schema.defaultValue})`
          : "";
      lines.push(`# ${schema.name}=${example}${defaultNote}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

const URL_EXAMPLES: Record<string, string> = {
  DATABASE_URL: "postgres://user:password@localhost:5432/dbname",
  REDIS_URL: "redis://localhost:6379",
  REDIS_URI: "redis://localhost:6379",
  MONGO_URL: "mongodb://localhost:27017/dbname",
  MONGO_URI: "mongodb://localhost:27017/dbname",
  MONGODB_URL: "mongodb://localhost:27017/dbname",
  MONGODB_URI: "mongodb://localhost:27017/dbname",
  AMQP_URL: "amqp://localhost:5672",
  RABBITMQ_URL: "amqp://localhost:5672",
  ELASTICSEARCH_URL: "http://localhost:9200",
};

function exampleValue(schema: EnvVarSchema): string {
  if (schema.defaultValue !== undefined) return schema.defaultValue;

  if (schema.type === "url") {
    return URL_EXAMPLES[schema.name] ?? "https://example.com";
  }

  switch (schema.type) {
    case "string":
      return `your_${schema.name.toLowerCase()}`;
    case "number":
    case "integer":
      return "0";
    case "port":
      return "3000";
    case "boolean":
      return "true";
    case "email":
      return "user@example.com";
    case "enum":
      return schema.enumValues?.[0] ?? "value";
  }
}
